### ISSUE TITLE
File not found VstsTaskSdk\VstsTaskSdk.psd1

### ISSUE THREAD

**Issue by acesyde** [sboulema/VsixTools#15]
Hi @sboulema 

I want to use your extension for update my vsix version.

```yaml
  - task: VsixToolsUpdateVersion@2
    displayName: "Set Vsix Version"
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    inputs:
      FileName: 'src/Tools.VisualStudio.Extension.ConfigManager/source.extension.vsixmanifest'
      VersionNumber: '$(GitVersion.NuGetVersion)'
```

But when I run my pipeline this error occured :

```
Starting: Set Vsix Version
==============================================================================
Task         : Vsix Tools - Update version
Description  : Set vsix version.
Version      : 2.4.44
Author       : Samir L. Boulema
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=SamirBoulema.Vsix-Tools)
==============================================================================
##[error]File not found: 'd:\a\_tasks\VsixToolsUpdateVersion_8aa837cb-7cd5-45f5-b7df-3ed54593621a\2.4.44\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
Finishing: Set Vsix Version
```
In vsix for update version tasks `ps_modules` is missing

![image](https://user-images.githubusercontent.com/958435/66185095-93b6a880-e67e-11e9-9699-a84c17aea684.png)

Can you help me ?

Thank you
